version: '3.8'

services:
  postgres:
    image: postgres
    container_name: quiz_postgres
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: quiz_redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: quiz_api
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

  quizpollapi:
    image: quizpollapi
    build:
      context: .
      dockerfile: QuizPollApi/Dockerfile

  api-1:
    image: api-1
    build:
      context: .
      dockerfile: Api/Dockerfile
